// 布克图书奖（The Booker Prize）历届获奖图书 · 英国文学最高荣誉
export interface BookerWinner {
  year: string;
  title: string;
  author: string;
}

export const BOOKER_OFFICIAL_URL = "https://thebookerprizes.com";

// 按年份倒序（最近在前）；1974/1992/2019 为双得主
export const BOOKER_WINNERS: BookerWinner[] = [
  { year: "2025", title: "Flesh", author: "David Szalay" },
  { year: "2024", title: "Orbital", author: "Samantha Harvey" },
  { year: "2023", title: "Prophet Song", author: "Paul Lynch" },
  { year: "2022", title: "The Seven Moons of Maali Almeida", author: "Shehan Karunatilaka" },
  { year: "2021", title: "The Promise", author: "Damon Galgut" },
  { year: "2020", title: "Shuggie Bain", author: "Douglas Stuart" },
  { year: "2019", title: "Girl, Woman, Other", author: "Bernardine Evaristo" },
  { year: "2019", title: "The Testaments", author: "Margaret Atwood" },
  { year: "2018", title: "Milkman", author: "Anna Burns" },
  { year: "2017", title: "Lincoln in the Bardo", author: "George Saunders" },
  { year: "2016", title: "The Sellout", author: "Paul Beatty" },
  { year: "2015", title: "A Brief History of Seven Killings", author: "Marlon James" },
  { year: "2014", title: "The Narrow Road to the Deep North", author: "Richard Flanagan" },
  { year: "2013", title: "The Luminaries", author: "Eleanor Catton" },
  { year: "2012", title: "Bring Up the Bodies", author: "Hilary Mantel" },
  { year: "2011", title: "The Sense of an Ending", author: "Julian Barnes" },
  { year: "2010", title: "The Finkler Question", author: "Howard Jacobson" },
  { year: "2009", title: "Wolf Hall", author: "Hilary Mantel" },
  { year: "2008", title: "The White Tiger", author: "Aravind Adiga" },
  { year: "2007", title: "The Gathering", author: "Anne Enright" },
  { year: "2006", title: "The Inheritance of Loss", author: "Kiran Desai" },
  { year: "2005", title: "The Sea", author: "John Banville" },
  { year: "2004", title: "The Line of Beauty", author: "Alan Hollinghurst" },
  { year: "2003", title: "Vernon God Little", author: "DBC Pierre" },
  { year: "2002", title: "Life of Pi", author: "Yann Martel" },
  { year: "2001", title: "True History of the Kelly Gang", author: "Peter Carey" },
  { year: "2000", title: "The Blind Assassin", author: "Margaret Atwood" },
  { year: "1999", title: "Disgrace", author: "J. M. Coetzee" },
  { year: "1998", title: "Amsterdam", author: "Ian McEwan" },
  { year: "1997", title: "The God of Small Things", author: "Arundhati Roy" },
  { year: "1996", title: "Last Orders", author: "Graham Swift" },
  { year: "1995", title: "The Ghost Road", author: "Pat Barker" },
  { year: "1994", title: "How Late It Was, How Late", author: "James Kelman" },
  { year: "1993", title: "Paddy Clarke Ha Ha Ha", author: "Roddy Doyle" },
  { year: "1992", title: "The English Patient", author: "Michael Ondaatje" },
  { year: "1992", title: "Sacred Hunger", author: "Barry Unsworth" },
  { year: "1991", title: "The Famished Road", author: "Ben Okri" },
  { year: "1990", title: "Possession", author: "A. S. Byatt" },
  { year: "1989", title: "The Remains of the Day", author: "Kazuo Ishiguro" },
  { year: "1988", title: "Oscar and Lucinda", author: "Peter Carey" },
  { year: "1987", title: "Moon Tiger", author: "Penelope Lively" },
  { year: "1986", title: "The Old Devils", author: "Kingsley Amis" },
  { year: "1985", title: "The Bone People", author: "Keri Hulme" },
  { year: "1984", title: "Hotel du Lac", author: "Anita Brookner" },
  { year: "1983", title: "Life & Times of Michael K", author: "J. M. Coetzee" },
  { year: "1982", title: "Schindler's Ark", author: "Thomas Keneally" },
  { year: "1981", title: "Midnight's Children", author: "Salman Rushdie" },
  { year: "1980", title: "Rites of Passage", author: "William Golding" },
  { year: "1979", title: "Offshore", author: "Penelope Fitzgerald" },
  { year: "1978", title: "The Sea, the Sea", author: "Iris Murdoch" },
  { year: "1977", title: "Staying On", author: "Paul Scott" },
  { year: "1976", title: "Saville", author: "David Storey" },
  { year: "1975", title: "Heat and Dust", author: "Ruth Prawer Jhabvala" },
  { year: "1974", title: "The Conservationist", author: "Nadine Gordimer" },
  { year: "1974", title: "Holiday", author: "Stanley Middleton" },
  { year: "1973", title: "The Siege of Krishnapur", author: "J. G. Farrell" },
  { year: "1972", title: "G.", author: "John Berger" },
  { year: "1971", title: "In a Free State", author: "V. S. Naipaul" },
  { year: "1970", title: "The Elected Member", author: "Bernice Rubens" },
  { year: "1969", title: "Something to Answer For", author: "P. H. Newby" },
];
