// 约 100 种音乐类型：中文标签 → Wikimedia Commons 检索词
export const GENRES: [string, string][] = [
  ["古典钢琴", "classical piano"],
  ["交响乐", "symphony"],
  ["小提琴", "violin"],
  ["大提琴", "cello"],
  ["吉他独奏", "solo guitar"],
  ["民谣", "folk"],
  ["爵士", "jazz"],
  ["蓝调", "blues"],
  ["灵魂乐", "soul"],
  ["放克", "funk"],
  ["摇滚", "rock"],
  ["金属", "metal"],
  ["朋克", "punk"],
  ["另类", "alternative"],
  ["独立", "indie"],
  ["流行", "pop"],
  ["电子", "electronic"],
  ["氛围", "ambient"],
  ["实验", "experimental"],
  ["嘻哈", "hip hop"],
  ["说唱", "rap"],
  ["节奏布鲁斯", "r&b"],
  ["雷鬼", "reggae"],
  ["乡村", "country"],
  ["口琴布鲁斯", "blues harp"],
  ["弗拉门戈", "flamenco"],
  ["探戈", "tango"],
  ["波萨诺瓦", "bossa nova"],
  ["桑巴", "samba"],
  ["萨尔萨", "salsa"],
  ["圣歌", "hymn"],
  ["合唱", "choral"],
  ["歌剧", "opera"],
  ["咏叹调", "aria"],
  ["室内乐", "chamber music"],
  ["巴洛克", "baroque"],
  ["浪漫主义", "romantic"],
  ["现代主义", "modernist"],
  ["极简主义", "minimalist"],
  ["电子舞曲", "EDM"],
  ["浩室", "house music"],
  ["科技舞曲", "techno"],
  ["鼓打贝斯", "drum and bass"],
  ["陷阱", "trap music"],
  ["迷幻", "psychedelic"],
  ["环境电子", "ambient electronic"],
  ["新世纪", "new age"],
  ["凯尔特", "celtic"],
  ["世界音乐", "world music"],
  ["非洲鼓", "african drum"],
  ["西塔琴", "sitar"],
  ["日本传统", "japanese traditional"],
  ["中国民乐", "chinese folk"],
  ["古琴", "guqin"],
  ["笛子", "chinese flute"],
  ["二胡", "erhu"],
  ["扬琴", "yangqin"],
  ["埙", "xun"],
  ["钢琴二重奏", "piano duet"],
  ["管风琴", "organ"],
  ["手风琴", "accordion"],
  ["班卓琴", "banjo"],
  ["曼陀林", "mandolin"],
  ["竖琴", "harp"],
  ["萨克斯", "saxophone"],
  ["小号", "trumpet"],
  ["长号", "trombone"],
  ["大号", "tuba"],
  ["圆号", "french horn"],
  ["长笛", "flute"],
  ["单簧管", "clarinet"],
  ["双簧管", "oboe"],
  ["巴松管", "bassoon"],
  ["打击乐", "percussion"],
  ["架子鼓", "drum kit"],
  ["定音鼓", "timpani"],
  ["马林巴", "marimba"],
  ["木琴", "xylophone"],
  ["电吉他", "electric guitar"],
  ["贝斯", "bass guitar"],
  ["尤克里里", "ukulele"],
  ["键盘", "keyboard"],
  ["合成器", "synthesizer"],
  ["雨声", "rain sound"],
  ["海浪", "ocean wave"],
  ["白噪音", "white noise"],
  ["冥想", "meditation"],
  ["放松", "relaxation"],
  ["睡眠", "sleep music"],
  ["瑜伽", "yoga"],
  ["专注", "focus music"],
  ["学习", "study music"],
  ["咖啡馆", "cafe music"],
  ["复古", "retro"],
  ["电影配乐", "film score"],
  ["游戏音乐", "game music"],
  ["圣诞", "christmas"],
  ["摇篮曲", "lullaby"],
  /* ===== 戏曲 ===== */
  ["京剧", "Peking opera"],
  ["昆曲", "Kunqu opera"],
  ["越剧", "Yue opera"],
  ["黄梅戏", "Huangmei opera"],
  ["豫剧", "Henan opera"],
  ["评剧", "Pingju"],
  ["粤剧", "Cantonese opera"],
  ["秦腔", "Qinqiang"],
  ["川剧", "Sichuan opera"],
  ["河北梆子", "Hebei clapper opera"],
];
